[package]
name = "bevy_text"
version = "0.14.1"
edition = "2021"
description = "Provides text functionality for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[features]
default_font = []

[dependencies]
# bevy
bevy_app = { path = "../bevy_app", version = "0.14.1" }
bevy_asset = { path = "../bevy_asset", version = "0.14.1" }
bevy_color = { path = "../bevy_color", version = "0.14.2" }
bevy_derive = { path = "../bevy_derive", version = "0.14.1" }
bevy_ecs = { path = "../bevy_ecs", version = "0.14.1" }
bevy_math = { path = "../bevy_math", version = "0.14.1" }
bevy_reflect = { path = "../bevy_reflect", version = "0.14.1", features = [
  "bevy",
] }
bevy_render = { path = "../bevy_render", version = "0.14.1" }
bevy_sprite = { path = "../bevy_sprite", version = "0.14.1" }
bevy_transform = { path = "../bevy_transform", version = "0.14.1" }
bevy_window = { path = "../bevy_window", version = "0.14.1" }
bevy_utils = { path = "../bevy_utils", version = "0.14.1" }

# other
cosmic-text = "0.12"
thiserror = "1.0"
serde = { version = "1", features = ["derive"] }
unicode-bidi = "0.3.13"
sys-locale = "0.3.0"

[dev-dependencies]
approx = "0.5.1"

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--cfg", "docsrs"]
all-features = true
